apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-deployment
  labels:
    app: menu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
      - name: menu
        image: nicolas2029/get-menu:alpine
        ports:
        - containerPort: 3001
        env:
        - name: MENU-PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: postgres-root-password
        - name: MENU-USER
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: postgres-root-user
        - name: MENU-NAME-DB
          valueFrom:
            configMapKeyRef:
              name: postgres-db-configmap
              key: postgres-database
        - name: MENU-HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-db-configmap
              key: postgres-url
---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
spec:
  selector:
    app: menu
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001