apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-admin-deployment
  labels:
    app: menu-admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menu-admin
  template:
    metadata:
      labels:
        app: menu-admin
    spec:
      containers:
      - name: menu-admin
        image: nicolas2029/menu-admin:alpine
        ports:
        - containerPort: 3000
        env:
        - name: MENU-PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: postgres-root-password
        - name: MENU-USER
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: postgres-root-user
        - name: MENU-RSA
          valueFrom:
            secretKeyRef:
              name: ssh-key-secret
              key: ssh-privatekey
        - name: MENU-RSA-PUB
          valueFrom:
            secretKeyRef:
              name: ssh-key-secret
              key: ssh-publickey
        - name: MENU-NAME-DB
          valueFrom:
            configMapKeyRef:
              name: postgres-db-configmap
              key: postgres-database
        - name: MENU-HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-db-configmap
              key: postgres-url
        resources:
          limits:
            memory: "2G"
            cpu: 2
            hugepages-2Mi: "200Mi"
          requests:
            memory: "2G"
            cpu: 2
            hugepages-2Mi: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: menu-admin-service
spec:
  selector:
    app: menu-admin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000